# Generated by Django 5.2 on 2025-04-22 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_contraseña_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientedesayuno',
            name='desayuno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.desayuno'),
        ),
    ]
