# Generated by Django 5.2 on 2025-04-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ingredientedesayuno_desayuno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desayuno',
            name='disponibilidad',
            field=models.BooleanField(default=False),
        ),
    ]
